---
  name: Bump Version

  on:
    workflow_dispatch:
    pull_request:

  jobs:
    bump-version:
      name: Bump Version
      uses: isomorphiclabs/github-actions-workflows/.github/workflows/bump-version.yaml@main
      secrets: inherit
      with:
        project-root: ./src
        commit-message: Bump Version
        python-version: '3.10'